// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:string):Promise<Array<main.Task>>;

export function GetTasks():Promise<Array<main.Task>>;
